services:
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env   # ✅ ADD THIS
    depends_on:
      - backend
